ignore:
  - vulnerability: CVE-2026-11822
    package:
      name: libsqlite3-0
      type: deb
  - vulnerability: CVE-2026-11824
    package:
      name: libsqlite3-0
      type: deb
  - vulnerability: CVE-2026-54369
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-54370
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-41992
    package:
      name: gzip
      type: deb
